### ISSUE TITLE
Can't make it appear in NEwRelic

### ISSUE THREAD

**Issue by ericfranckx** [eksoverzero/newrelic_mongodb_agent#1]
Hi,
I install the plugin
start i t:  bundle exec foreman start
15:40:27 mongodb.1 | started with pid 20521
15:40:27 mongodb.1 | Faraday: you may want to install system_timer for reliable timeouts

but can see data in Newrelic.
I have set the proxy settings in the config file but nothing ... :-(

IS there a wait to set a log file destination, trace what is doing by the plugin ?

Regards,

Eric

**Comment by eksoverzero** [comment]
Foreman, which uses the `Procfile` has been taken out of this version. The original this uses it though: https://github.com/MongoHQ/newrelic-mongodb-agent

Here you'd need the use `./newrelic_mongodb_agent.daemon run` to run the plugin in the foreground or `newrelic_mongodb_agent.daemon start` and `newrelic_mongodb_agent.daemon stop` to start and stop the plugin running in the background

**Comment by ericfranckx** [comment]
Hi,
Thanks Will test when back from holiday

Regards

On Tuesday, 12 August 2014, Steven Eksteen notifications@github.com wrote:

> Foreman, which uses the Procfile has been taken out of this version. The
> original this uses it though:
> https://github.com/MongoHQ/newrelic-mongodb-agent
> 
> Here you'd need the use ./newrelic_mongodb_agent.daemon run to run the
> plugin in the foreground or newrelic_mongodb_agent.daemon start and newrelic_mongodb_agent.daemon
> stop to start and stop the plugin running in the background
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/secondimpression/newrelic_mongodb_agent/issues/1#issuecomment-51978941
> .

## 

Sent from Gmail Mobile

## 

---

This email is sent on behalf of Northgate Information Solutions Limited and 
its associated companies ("Northgate") and is strictly confidential and 
intended solely for the addressee(s). 

If you are not the intended recipient of this email you must: (i) not 
disclose, copy or distribute its contents to any other person nor use its 
contents in any way or you may be acting unlawfully;  (ii) contact 
Northgate immediately on +44 (0)1442 232424 quoting the name of the sender 
and the addressee then delete it from your system.

Northgate has taken reasonable precautions to ensure that no viruses are 
contained in this email, but does not accept any responsibility once this 
email has been transmitted.  You should scan attachments (if any) for 

## viruses.
