### ISSUE TITLE
Not able to startup teh newrelic agent for MongoDB

### ISSUE THREAD

**Issue by sameer59-saks** [eksoverzero/newrelic_mongodb_agent#2]
I am having trouble starting up the newrelic agent for mongodb and getting the error mentioned below while starting it up.
After completing all the configurations for Newrelic with Mongo we are not abel to start the newrelic agent. it gives the error 
[root@sd1pxx14lx init.d]# ./newrelic-plugin-agent start 
usage: newrelic-plugin-agent [-h] [-c CONFIG] [-f] [-C] 
newrelic-plugin-agent: error: unrecognized arguments: start

Plugin name : newrelic_plugin_agent-1.3.0.tar.gz

Quick response will be appreciated.

Regards,
Sameer varpe

**Comment by eksoverzero** [comment]
Use need to use the daemon to start:

./newrelic_mongodb_agent.daemon start

**Comment by sameer59-saks** [comment]
HI eksoverzero,

I was able to startup the newrelic agent specifying the config file while starting it.  However there is new problem that i am facing right now is regarding the mongo plugin

```
from pymongo import errors
```

ImportError: No module named pymongo
ERROR      2014-08-28 11:42:06,470 60110  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L276   : Enabled plugin mongodb not available
WARNING    2014-08-28 11:42:06,470 60110  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L217   : No metrics to send to NewRelic this interval
INFO       2014-08-28 11:42:06,470 60110  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.00 seconds, next wake in 59 seconds
INFO       2014-08-28 11:43:06,470 60110  MainProcess     MainThread newrelic_plugin_agent.agent                   start_plugin_polling      L263   : Enabling plugin: mongodb
ERROR      2014-08-28 11:43:06,470 60110  MainProcess     MainThread newrelic_plugin_agent.agent                   _get_plugin               L256   : Attempting to import newrelic_plugin_agent.plugins.mongodb.M

It will be great if someone can share the plugin with me, the platform I am using is
Linux 2.6.32-358.6.1.el6.x86_64 #1 SMP  x86_64 x86_64 x86_64 GNU/Linux

Thanks in advance
Regards,
Sameer varpe

**Comment by eksoverzero** [comment]
I don't think you are using this repo's code.

The above is a Python error. This repo is written in Ruby

**Comment by sameer59-saks** [comment]
Hi eksoverzero

I downloaded the mongo-python-driver and installed it and the issue is resolved now. Thanks for your comments it helped me find a direction.https://github.com/mongodb/mongo-python-driver

Regards,
Sameer Varpe

**Comment by sameer59-saks** [comment]
Now my next task s to utilize the the newrelic agent and pymongo driver that I have isntalled. It would be great if you could put some insight onto as what configuration that I need to do, so that I can utilize the setups that I have done.

Regards,
Sameer varpe
